from typing import Any, Unpack, overload

from aiogram.fsm.storage.base import BaseStorage, StateType, StorageKey

from src.bot.fsm_data import FSMData

class FSMContext:
    def __init__(self, storage: BaseStorage, key: StorageKey) -> None: ...
    async def set_state(self, state: StateType = None) -> None: ...
    async def get_state(self) -> str | None: ...
    async def set_data(self, data: FSMData) -> None: ...
    async def get_data(self) -> FSMData: ...
    @overload
    async def get_value(self, key: str) -> Any | None: ...
    @overload
    async def get_value(self, key: str, default: Any) -> Any: ...
    async def get_value(self, key: str, default: Any | None = None) -> Any | None: ...
    async def update_data(self, data: FSMData | None = None, **kwargs: Unpack[FSMData]) -> FSMData: ...
    async def clear(self) -> None: ...
