from typing import Any, Optional, Unpack, overload

from aiogram.fsm.storage.base import BaseStorage, StateType, StorageKey
from src.bot.fsm_data import FSMData

class FSMContext:
    def __init__(self, storage: BaseStorage, key: StorageKey) -> None: ...

    async def set_state(self, state: StateType = None) -> None: ...

    async def get_state(self) -> Optional[str]: ...

    async def set_data(self, data: FSMData) -> None: ...

    async def get_data(self) -> FSMData: ...

    @overload
    async def get_value(self, key: str) -> Optional[Any]: ...

    @overload
    async def get_value(self, key: str, default: Any) -> Any: ...

    async def get_value(self, key: str, default: Optional[Any] = None) -> Optional[Any]: ...

    async def update_data(
        self, data: Optional[FSMData] = None, **kwargs: Unpack[FSMData]
    ) -> FSMData: ...

    async def clear(self) -> None: ...
