version: 2
updates:
  # Enable version updates for python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # TODO: switch to uv
      poetry: # currently can't switch to uv because of https://github.com/dependabot/dependabot-core/issues/10478
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
