services:
  api:
    build: .
    volumes:
      - "./settings.yaml:/code/settings.yaml:ro" # Read-only settings file
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8000:8000"
  
  db:
    # See more: https://registry.hub.docker.com/_/mongo
    image: "mongo:8.0"
    restart: always
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/db --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}
  

volumes:
  mongodb:
