[project]
name = "printers"
version = "0.1.0"
description = ""
authors = [{ name = "one-zero-eight" }]
urls = { homepage = "https://t.me/one_zero_eight" }
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "joserfc>=1.6.5",
    "colorlog>=6.10.1",
    "cryptography>=48.0.0",
    "fastapi>=0.136.1",
    "fastapi-swagger>=0.4.49",
    "gunicorn>=26.0.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "ruff>=0.15.12",
    "uvicorn>=0.46.0",
    "pycups>=2.0.4",
    "unoserver>=3.6",
    "python-multipart>=0.0.27",
    "pyipp>=0.17.2",
    "aiogram>=3.27.0",
    "pypdf2>=3.0.1",
    "beautifulsoup4>=4.14.3",
    "cachetools>=7.1.1",
    "aiogram-media-group>=0.5.1",
    "aiohttp-socks>=0.11.0",
    "docaligner-docsaid>=1.1.1",
    "pymupdf>=1.27.2.3",
    "prek>=0.3.13",
]

[dependency-groups]
dev = ["pytest>=9.0.3"]
mongo = ["beanie>=1.30.0,<2", "motor>=3.7.1,<4"]

[tool.uv]
default-groups = ["mongo"]
constraint-dependencies = ["urllib3>=2.7.0"]

[tool.ruff]
line-length = 120
lint.extend-select = ["I", "UP", "PL"]
lint.extend-ignore = ["PLC0415", "PLR"]
exclude = ["*.pyi", "auto_crop.py"]
target-version = "py313"

[tool.pyright]
include = ["src"]
exclude = ["**/node_modules", "**/__pycache__"]
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
stubPath = "typings"
reportMissingImports = true
reportMissingTypeStubs = false
reportOptionalMemberAccess = false
