$schema: https://json-schema.org/draft-07/schema
$defs:
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: $Schema
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  database_uri:
    description: MongoDB database settings
    examples:
    - mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin
    - mongodb://mongoadmin:secret@db:27017/db?authSource=admin
    format: password
    title: Database Uri
    type: string
    writeOnly: true
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  cups_server_host:
    default: 127.0.0.1
    description: CUPS server host
    title: Cups Server Host
    type: string
  cups_server_port:
    default: 631
    description: CUPS server port
    title: Cups Server Port
    type: integer
  cups_server_admin_user:
    default: admin
    description: CUPS server admin user
    title: Cups Server Admin User
    type: string
  cups_server_admin_password:
    anyOf:
    - format: password
      type: string
      writeOnly: true
    - type: 'null'
    default: null
    title: Cups Server Admin Password
  innohassle_api_url:
    default: https://api.innohassle.ru/accounts/v0
    description: URL of the Accounts API
    title: Innohassle Api Url
    type: string
  innohassle_api_jwt_token:
    description: JWT token for accessing the Accounts API as a service
    format: password
    title: Innohassle Api Jwt Token
    type: string
    writeOnly: true
required:
- database_uri
- innohassle_api_jwt_token
title: Settings
type: object
