name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       Check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      #----------------------------------------------
      #       Install uv
      #----------------------------------------------
      # based on https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      #----------------------------------------------
      #  Install project dependencies if not cached
      #----------------------------------------------

      - name: Load pre-commit caches
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install libcups2-dev
        run: sudo apt-get update && sudo apt-get install libcups2-dev

      - name: Run pre-commit
        run: uvx pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual
        env:
          RUFF_FORMAT: github
